
export const privilegesEnum = {
  User: "User",
  UserCreate: "User_create",
  UserUpdate: "User_update",
  UserDelete: "User_delete",
  Role: "Role",
  RoleCreate: "Role_create",
  RoleUpdate: "Role_update",
  RoleDelete: "Role_delete",
  AssignPrivilege: "Assign_privilege",
  Complaint: 'Complaint',
  ComplaintCreate: 'Complaint_create',
  ComplaintShow: 'Complaint_show',
  ComplaintStatusUpdate : 'Complaint_status_update',
  CommentCreate: 'Comment_create',
  Category        : 'Category',
  CategoryCreate : 'Category_create',
  CategoryShow   : 'Category_show',
  CategoryEdit   : 'Category_edit',
  CategoryDelete: 'Category_delete',
  Reports: "Reports",
  ComplaintsByStatusReport:'Complaints_by_status_report',
  ComplaintsByPriorityReport:'Complaints_by_priority_report',   
  AverageResolutionTimeReport:'Average_resolution_time_report',
  ComplaintsTrendReport:'Complaints_trend_report',
  
};
